Add version bump workflow

diff --git a/.github/workflows/version-bump.yml b/.github/workflows/version-bump.yml
--- a/.github/workflows/version-bump.yml
+++ b/.github/workflows/version-bump.yml
@@ -1,14 +1,16 @@
-name: Package Version Bump
+name: Commit Version Bump
 
 on:
-    release:
-        types: 
-            - published
+    workflow_run:
+      workflows: [Publish NPM Package]
+      types:
+        - completed
 
 jobs:
-    version:
+    bump-version:
         name: Version Bump
         runs-on: ubuntu-latest
+        if: ${{ github.event.workflow_run.conclusion == 'success' }}
         steps:
             - uses: actions/checkout@v3
               with:
@@ -19,8 +21,16 @@ jobs:
                   node-version: 20.x
             - uses: fregante/setup-git-user@v2
 
-            - name: Bump Version
+            - name: Commit Bump
               run: npm version prerelease -m "Bump version to %s"
             
             - name: Push Changes
               run: git push
+        
+    on-failure:
+        name: Version Bump Failure
+        runs-on: ubuntu-latest
+        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        steps:    
+            - run: echo "Failed to bump version. Check triggering workflow for errors."
+            - run: exit 1
